---

_You are currently looking at **version 1.5** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

# Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [1]:
import pandas as pd
def energy_file():
    energy_df= pd.read_excel('Energy Indicators.xls',skiprows=16)
    del energy_df['Unnamed: 0']
    del energy_df['Unnamed: 1']
    energy_df.rename(columns={'Unnamed: 2':'Country','Renewable Electricity Production':'% Renewable'}, inplace=True)
    energy_df = energy_df.drop(0)
    energy_df['Energy Supply'] = pd.to_numeric(energy_df['Energy Supply'], errors='coerce')
    energy_df['Energy Supply per capita'] = pd.to_numeric(energy_df['Energy Supply per capita'], errors='coerce')
    energy_df.rename(columns={'Energy Supply per capita':'Energy Supply per Capita'}, inplace=True)
    
    energy_df['Energy Supply'] = energy_df['Energy Supply']* 1000000
    energy_df.set_index('Country',inplace=True)
    names_with_bracket = energy_df.index.str.split('\s\(') # split the index by '('
    #print(names_with_bracket)
    
    energy_df.index = names_with_bracket.str[0] # the [0] element is the country name (new index) 
    energy_df['ID'] = names_with_bracket.str[0] 
    #names_with_number = energy_df.index.str.split('\s\[^0-9]') # split the index by '0'
    
    energy_df['ID'].replace(to_replace="[\d]", value="", regex=True, inplace=True)

    energy_df['ID'].replace(to_replace="Republic of Korea", value="South Korea", inplace=True)
    energy_df['ID'].replace(to_replace="United States of America", value="United States",inplace=True)
    energy_df['ID'].replace(to_replace="United Kingdom of Great Britain and Northern Ireland", value="United Kingdom",inplace=True)
    energy_df['ID'].replace(to_replace="China, Hong Kong Special Administrative Region", value="Hong Kong",inplace=True)
    energy_df.set_index('ID',inplace=True)
    #print(names_with_number)
    return energy_df
def gdp_file():
    gdp_df= pd.read_csv('world_bank.csv',skiprows=4)
    gdp_df['Country Name'].replace(to_replace="Korea, Rep.", value="South Korea", inplace=True)
    gdp_df['Country Name'].replace(to_replace="Iran, Islamic Rep.",value="Iran", inplace=True)
    gdp_df['Country Name'].replace(to_replace="Hong Kong SAR, China", value="Hong Kong", inplace=True)
    gdp_df.set_index('Country Name',inplace=True)
    gdp_df = gdp_df.ix[:,49:63]
    return gdp_df 

def sci_file():
    ScimEn_df= pd.read_excel('scimagojr-3.xlsx')
    ScimEn_df.set_index('Country',inplace=True)
    return ScimEn_df

def answer_one():
    energy_df =energy_file()
    gdp_df = gdp_file()
    ScimEn_df = sci_file()
   
    
    
    final_df = pd.merge(ScimEn_df,energy_df,how='inner',left_index=True,right_index=True)
    final_df = pd.merge(final_df,gdp_df,how='inner',left_index=True,right_index=True)
    final_df = final_df.where(final_df['Rank']<=15)
    return final_df.sort_values('Rank').dropna(how='all')


answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,1.271910e+11,93.0,19.7549,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,9.083800e+10,286.0,11.571,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,1.898400e+10,149.0,10.2328,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7.920000e+09,124.0,10.6005,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,3.070900e+10,214.0,17.2887,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,1.043100e+10,296.0,61.9454,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,1.326100e+10,165.0,17.9015,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,3.319500e+10,26.0,14.9691,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,1.059700e+10,166.0,17.0203,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,1.100700e+10,221.0,2.27935,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6.530000e+09,109.0,33.6672,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4.923000e+09,106.0,37.9686,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9.172000e+09,119.0,5.70772,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5.386000e+09,231.0,11.8108,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,1.214900e+10,59.0,69.648,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [2]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [8]:
def answer_two():
    import numpy as np
    energy_df =energy_file().dropna(how='all')#.reset_index()
    gdp_df = gdp_file().dropna(how='all')#.reset_index()
    ScimEn_df = sci_file().dropna(how='all')#.reset_index()

    
    #missing_energy_rows = energy_df[~energy_df['ID'].isin(ScimEn_df['Country'])].count()
    #missing_gdp_rows = gdp_df[~gdp_df['Country Name'].isin(ScimEn_df['Country'])].count()
    #missing_sci_rows = ScimEn_df[~ScimEn_df['Country'].isin(energy_df['ID'])].count()

    merged_df = pd.merge(energy_df, gdp_df, how='outer',left_index=True,right_index=True).merge(ScimEn_df, how='outer',left_index=True,right_index=True)

    result = merged_df.loc[~merged_df.index.isin(merged_df.dropna().index)]

    #missing_rows = gdp_df[~ScimEn_df['Country'].isin(gdp_df['Country Name'])]
    
    #print(len(ScimEn_df.index))
    #print(len(energy_df.index))
    #print(len(gdp_df.index))
    
    #missing_rows = abs(len(ScimEn_df.index)- len(energy_df.index))
    #final_df = pd.merge(ScimEn_df,energy_df,how='inner',left_index=True,right_index=True)
    
    #missing_rows += abs((len(final_df.index) - len(gdp_df.index)))
    
    return len(result) # np.int(missing_energy_rows[0] + missing_gdp_rows[0] + missing_sci_rows[0])
(answer_two())

,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
American Samoa,NaN,NaN,0.641026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,1.0,1.0,0.0,0.0,0.00,0.0
Andorra,9.000000e+06,121.0,88.6957,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN,168.0,2.0,2.0,13.0,0.0,6.50,1.0
Anguilla,2.000000e+06,136.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Arab World,NaN,NaN,NaN,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Argentina,3.378000e+09,79.0,24.0645,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN,40.0,1223.0,1213.0,10620.0,1654.0,8.68,47.0
Aruba,1.200000e+07,120.0,14.8707,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bahamas,4.500000e+07,118.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Bahamas, The",NaN,NaN,NaN,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bermuda,6.000000e+06,88.0,0,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN,174.0,2.0,2.0,12.0,0.0,6.00,1.0
"Bonaire, Sint Eustatius and Saba",5.000000e+06,213.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
British Indian Ocean Territory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179.0,1.0,1.0,37.0,0.0,37.00,1.0
British Virgin Islands,2.000000e+06,85.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cabo Verde,7.000000e+06,15.0,21.2276,1.352564e+09,1.557757e+09,1.661356e+09,1.640250e+09,1.664311e+09,1.730364e+09,1.749085e+09,1.767367e+09,1.816851e+09,1.862692e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0,3.0,3.0,5.0,0.0,1.67,1.0
Caribbean small states,NaN,NaN,NaN,5.897028e+10,6.088163e+10,6.172341e+10,5.952123e+10,5.963144e+10,6.032654e+10,6.104798e+10,6.184883e+10,6.264199e+10,6.347025e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cayman Islands,8.000000e+06,131.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0,2.0,2.0,2.0,0.0,1.00,1.0
Central African Republic,2.300000e+07,5.0,85.6354,1.774985e+09,1.856768e+09,1.894909e+09,1.927297e+09,1.986015e+09,2.051568e+09,2.111034e+09,1.329699e+09,1.312983e+09,1.385019e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Central Europe and the Baltics,NaN,NaN,NaN,1.210991e+12,1.289104e+12,1.336368e+12,1.286232e+12,1.311611e+12,1.352416e+12,1.359737e+12,1.377044e+12,1.415218e+12,1.463305e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"China, Macao Special Administrative Region",4.700000e+07,83.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Christmas Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.0,1.0,1.0,0.0,0.0,0.00,0.0
Comoros,5.000000e+06,7.0,11.6279,4.902586e+08,4.941814e+08,4.961594e+08,5.058345e+08,5.169629e+08,5.304039e+08,5.463160e+08,5.654371e+08,5.770944e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Congo,1.020000e+08,23.0,57.7489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.0,23.0,23.0,10.0,1.0,0.43,2.0
"Congo, Dem. Rep.",NaN,NaN,NaN,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Congo, Rep.",NaN,NaN,NaN,9.888363e+09,9.731907e+09,1.027419e+10,1.104156e+10,1.200788e+10,1.241862e+10,1.289053e+10,1.333406e+10,1.423810e+10,1.461490e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cook Islands,1.000000e+06,48.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cote d'Ivoire,NaN,NaN,NaN,2.263881e+10,2.303839e+10,2.362422e+10,2.439236e+10,2.488451e+10,2.379276e+10,2.634013e+10,2.876832e+10,3.122699e+10,3.386308e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cuba,5.850000e+08,51.0,0.663532,5.545431e+10,5.948147e+10,6.193022e+10,6.282767e+10,6.432820e+10,6.613130e+10,6.812475e+10,6.995461e+10,NaN,NaN,73.0,211.0,209.0,980.0,152.0,4.64,16.0
Curaçao,7.800000e+07,502.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Côte d'Ivoire,5.470000e+08,25.0,22.8228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Côte d’Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132.0,10.0,9.0,101.0,4.0,10.10,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
South Asia (IDA & IBRD),NaN,NaN,NaN,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Sudan,2.800000e+07,2.0,0.423729,NaN,NaN,1.419283e+10,1.490838e+10,1.572736e+10,1.499756e+10,8.086368e+09,9.148087e+09,9.456711e+09,8.856231e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
St. Kitts and Nevis,NaN,NaN,NaN,7.078789e+08,7.279287e+08,7.579826e+08,7.155482e+08,6.924574e+08,7.041954e+08,6.955641e+08,7.360467e+08,7.868565e+08,8.231943e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
St. Lucia,NaN,NaN,NaN,1.234739e+09,1.242412e+09,1.277116e+09,1.271323e+09,1.249497e+09,1.258266e+09,1.244975e+09,1.246701e+09,1.252387e+09,1.274435e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
St. Vincent and the Grenadines,NaN,NaN,NaN,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State of Palestine,6.100000e+07,14.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub-Saharan Africa,NaN,NaN,NaN,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub-Saharan Africa (IDA & IBRD countries),NaN,NaN,NaN,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sub-Saharan Africa (excluding high income),NaN,NaN,NaN,1.106480e+12,1.184766e+12,1.247853e+12,1.283380e+12,1.354416e+12,1.412661e+12,1.464127e+12,1.533550e+12,1.604593e+12,1.652379e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Syrian Arab Republic,5.420000e+08,28.0,11.5683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,88.0,87.0,655.0,86.0,7.44,14.0
Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,6468.0,6441.0,86099.0,14768.0,13.31,102.0
Tanzania,NaN,NaN,NaN,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10,97.0,56.0,56.0,600.0,69.0,10.71,15.0
The former Yugoslav Republic of Macedonia,1.170000e+08,56.0,26.1405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Timor-Leste,7.000000e+06,6.0,0,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tonga,3.000000e+06,28.0,0,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turks and Caicos Islands,3.000000e+06,85.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tuvalu,NaN,NaN,0,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Republic of Tanzania,9.940000e+08,20.0,31.0728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United States Virgin Islands,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Upper middle income,NaN,NaN,NaN,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vanuatu,3.000000e+06,10.0,14.7059,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Venezuela,2.871000e+09,95.0,67.8345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,891.0,886.0,6109.0,693.0,6.86,41.0
"Venezuela, RB",NaN,NaN,NaN,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Viet Nam,2.554000e+09,28.0,45.3215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.0,261.0,258.0,1164.0,92.0,4.46,16.0
Vietnam,NaN,NaN,NaN,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wallis and Futuna Islands,0.000000e+00,26.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
West Bank and Gaza,NaN,NaN,NaN,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
World,NaN,NaN,NaN,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yemen,3.440000e+08,13.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,28.0,28.0,121.0,25.0,4.32,8.0
"Yemen, Rep.",NaN,NaN,NaN,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<br>

Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [4]:
def answer_three():
    Top15 = answer_one()
    Top15['avgGDP'] = Top15[[ '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1)
    return Top15.sort_values('avgGDP',ascending=False)['avgGDP']
    
answer_three()

United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
Name: avgGDP, dtype: float64

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [61]:
def answer_four():
    Top15 = answer_one()
    Top15['avgGDP'] = Top15[[ '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1)
    Top15['GDP_RANK'] = Top15['avgGDP'].rank(ascending=False)
    gdpChange = (Top15[Top15['GDP_RANK']==6]['2015']-Top15[Top15['GDP_RANK']==6]['2006'])
    return gdpChange[0]
answer_four()

246702696075.3999

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [62]:
def answer_five():
    Top15 = answer_one()
   
    return Top15['Energy Supply per Capita'].mean()
answer_five()

157.6

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [71]:
def answer_six():
    Top15 = answer_one()
    max_renewable = Top15.where(Top15['% Renewable'] == Top15['% Renewable'].max()).dropna()
    
    max_renewable.reset_index()
    
    return list(zip(max_renewable.index,max_renewable['% Renewable']))[0]

(answer_six())

('Brazil', 69.64803)

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [76]:
def answer_seven():
    Top15 = answer_one()
    Top15['ratio']= Top15['Self-citations']/Top15['Citations']
    max_ratio = Top15.where(Top15['ratio'] == Top15['ratio'].max()).dropna(how='all')
    return list(zip(max_ratio.index,max_ratio['ratio']))[0]
answer_seven()

('China', 0.68931261793894216)

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [90]:
def answer_eight():
    Top15 = answer_one()
    Top15['pop_estimate'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15['pop_rank'] = Top15['pop_estimate'].rank(ascending=False)
    Third_Most = Top15[Top15['pop_rank']==3]
    return list(Third_Most.index)[0]
(answer_eight())

'United States'

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [10]:
def answer_nine():
    Top15 = answer_one()
    Top15['pop_estimate'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15['citable_doc_per_person'] = Top15['Citable documents']/Top15['pop_estimate']
    corr = Top15['citable_doc_per_person'].corr(Top15['Energy Supply per Capita'],method='pearson')

    return  corr
answer_nine()

0.79400104354429457

In [11]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

In [12]:
#plot9() # Be sure to comment out plot9() before submitting the assignment!

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [13]:
def answer_ten():
    import numpy as np
    Top15 = answer_one()
    median_renewable = Top15['% Renewable'].median()
    Top15['HighRenew'] = np.where(Top15['% Renewable'] >= median_renewable,1,0) 
                         
    return  Top15.sort_values('Rank')['HighRenew']
answer_ten()

China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int32

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [14]:
def add_continent():
    Top15 = answer_one()
    ContinentDict  = pd.Series({'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'})

    Top15['Continent']= ContinentDict
    return Top15

def answer_eleven():
    import numpy as np
    Top15 = add_continent()
   
    Top15['pop_estimate'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    continent_df = pd.DataFrame(index=['Asia', 'Australia', 'Europe', 'North America', 'South America'],
                                columns=['size', 'sum', 'mean', 'std'])
    #continent_df['Asia']
    _size = Top15.groupby('Continent').count()['pop_estimate']
    _sum = Top15.groupby('Continent').sum()['pop_estimate']
    _mean = Top15.groupby('Continent').mean()['pop_estimate']
    _std = Top15.groupby('Continent').std()['pop_estimate']
    continent_df['size'] = _size
    continent_df['sum'] = _sum
    continent_df['mean'] = _mean
    continent_df['std'] = _std
    
    #print(type(_size))
   
            
    return continent_df
    #return Top15.groupby('Continent').count()['Rank']
answer_eleven()

               size           sum          mean           std
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [15]:
def answer_twelve():
    Top15 = add_continent()
    Top15['bins'] = pd.cut(Top15['% Renewable'],5)
    #Top15.set_index(['Continent','bins'],inplace=True)
    groups = Top15.groupby(['Continent','bins']).count()['% Renewable'].dropna(how='all')
    
    return (groups)
(answer_twelve())

Continent      bins
Asia           (2.212, 15.753]     4.0
               (15.753, 29.227]    1.0
Australia      (2.212, 15.753]     1.0
Europe         (2.212, 15.753]     1.0
               (15.753, 29.227]    3.0
               (29.227, 42.701]    2.0
North America  (2.212, 15.753]     1.0
               (56.174, 69.648]    1.0
South America  (56.174, 69.648]    1.0
Name: % Renewable, dtype: float64

### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

In [16]:
def answer_thirteen():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['PopEst'] = Top15['PopEst'].map('{:,}'.format)
    return Top15['PopEst']
(answer_thirteen())

China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: PopEst, dtype: object

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [17]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")

In [18]:
#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!